// src/components/custom/full-modal.vue
<template>
  <Modal
    size="full"
    :hide-close-button="true"
    :is-open="isOpen"
    :is-dismissable="dissmissable"
    :on-open-change="onOpenChange"
    :is-keyboard-dismiss-disabled="true"
    class="overflow-clip"
  >
    <ModalContent>
      <ModalBody @click="onClose">
        <slot></slot>
      </ModalBody>
    </ModalContent>
  </Modal>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';
import { Modal, ModalContent, ModalBody } from '@nextui-org/react';

export default defineComponent({
  props: {
    dissmissable: {
      type: Boolean,
      required: true,
    },
    isOpen: {
      type: Boolean,
      required: true,
    },
    onOpenChange: {
      type: Function as PropType<() => void>,
      required: true,
    },
  },
});
</script>

// src/components/custom/full-modal.tsx
import { Modal, ModalContent, ModalBody } from "@nextui-org/react";
import React from "react";

export function FullModal({
  dissmissable,
  children,
  isOpen,
  onOpenChange,
}: {
  dissmissable: boolean;
  children: React.ReactNode;
  isOpen: boolean;
  onOpenChange: () => void;
}) {
  return (
    <Modal
      size="full"
      hideCloseButton
      isOpen={isOpen}
      isDismissable={dissmissable}
      onOpenChange={onOpenChange}
      isKeyboardDismissDisabled={true}
      className="overflow-clip"
    >
      <ModalContent>
        {(onClose) => <ModalBody onClick={onClose}>{children}</ModalBody>}
      </ModalContent>
    </Modal>
  );
}
